### ISSUE TITLE
checkstyle 配置在没有方法和类 javadoc 的场景下无法生效

### ISSUE THREAD

**Issue by A-Little-Excited** [paion-data/athena#35]
athena 项目中，没有对 createFileNameAndUploadedTimeBasedIdGenerator 该静态方法进行 Javadoc 检查

**Comment by QubitPi** [comment]
@A-Little-Excited https://github.com/paion-data/athena/pull/43 已经修复 checkstyle 的问题，目前在阿里云适配代码上有 checkstyle 报错，请代码的作者（ @A-Little-Excited  ）修复一下：

先确保当前分支没有未提交代码，然后：

```console
git checkout master
git checkout fix-cs
mvn clean verify
```
